/* global window */
// Auto-generated from TT_Master_Course_Directory_2026 (Google Sheet → CSV)

const CATEGORIES = [
  {
    "name": "Business & Entrepreneurship",
    "count": 23
  },
  {
    "name": "Technology & Digital",
    "count": 17
  },
  {
    "name": "Hospitality & Culinary",
    "count": 16
  },
  {
    "name": "Personal Development",
    "count": 12
  },
  {
    "name": "Creative Arts & Design",
    "count": 9
  },
  {
    "name": "Technical Trades",
    "count": 7
  },
  {
    "name": "Professional Development",
    "count": 7
  },
  {
    "name": "Business",
    "count": 6
  },
  {
    "name": "Health & Medical",
    "count": 6
  },
  {
    "name": "Finance & Accounting",
    "count": 3
  },
  {
    "name": "Law & Governance",
    "count": 2
  },
  {
    "name": "Agriculture & Environment",
    "count": 2
  },
  {
    "name": "Communication & Media",
    "count": 2
  },
  {
    "name": "Soft Skills",
    "count": 2
  },
  {
    "name": "Technology",
    "count": 1
  },
  {
    "name": "Engineering & Construction",
    "count": 1
  }
];

const INSTITUTIONS = [
  {
    "id": "cts",
    "name": "CTS College",
    "summary": "Private tertiary institution offering certifications, professional courses, and skills training.",
    "type": "Private",
    "website": "https://www.ctscollege.com",
    "location": "Trinidad",
    "courseCount": 44
  },
  {
    "id": "mic",
    "name": "MIC Institute of Technology (MIC-IT)",
    "summary": "Technical-vocational training and applied technology programmes across multiple campuses.",
    "type": "Technical",
    "website": "https://mic.co.tt",
    "location": "Trinidad",
    "courseCount": 4
  },
  {
    "id": "nedco",
    "name": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Supporting MSMEs through training, financing, and entrepreneurship development.",
    "type": "Government",
    "website": "https://nedco.gov.tt",
    "location": "Trinidad",
    "courseCount": 17
  },
  {
    "id": "thti",
    "name": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "The national institute for hospitality, tourism, culinary arts, and agro-processing training.",
    "type": "Public",
    "website": "https://www.thti.edu.tt",
    "location": "Chaguaramas",
    "courseCount": 16
  },
  {
    "id": "roytec",
    "name": "UWI-ROYTEC",
    "summary": "A UWI-affiliated tertiary college offering business, IT, and corporate training programmes.",
    "type": "Public",
    "website": "https://www.roytec.edu",
    "location": "Port of Spain",
    "courseCount": 2
  },
  {
    "id": "usc",
    "name": "University of the Southern Caribbean (USC)",
    "summary": "A liberal arts university offering undergraduate, graduate, and professional development programmes.",
    "type": "Private",
    "website": "https://www.usc.edu.tt",
    "location": "Maracas Royal Road",
    "courseCount": 12
  },
  {
    "id": "utt",
    "name": "University of Trinidad and Tobago (UTT)",
    "summary": "The national university focused on engineering, applied sciences, and professional development.",
    "type": "Public",
    "website": "https://utt.edu.tt",
    "location": "Multiple campuses",
    "courseCount": 6
  },
  {
    "id": "alj",
    "name": "Arthur Lok Jack Global School of Business",
    "summary": "The Caribbean's leading graduate business school — MBAs, executive education, and short courses.",
    "type": "Public",
    "website": "https://lokjackgsb.edu.tt",
    "location": "Mt Hope",
    "courseCount": 3
  },
  {
    "id": "shel",
    "name": "School of Higher Education Limited - SHEL",
    "summary": "Online self-paced professional development with international course catalogue.",
    "type": "Private",
    "website": "https://shel.edu.tt",
    "location": "Online",
    "courseCount": 15
  }
];

const COURSES = [
  {
    "id": "c001",
    "title": "Introduction to Java Programming",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn core Java programming concepts including object-oriented design, data structures, and application development",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$2,500.00",
    "startDate": "11 Jun 2026",
    "deadline": "3 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/news/course-schedule/23309",
    "featured": false
  },
  {
    "id": "c002",
    "title": "Certified Associate in Project Management (CAPM)",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Prepare for CAPM certification covering project management processes, scheduling, cost, risk, and quality",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "$3,000.00",
    "startDate": "11 Jun 2026",
    "deadline": "3 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/certified-associate-project-management",
    "featured": false
  },
  {
    "id": "c003",
    "title": "Microsoft Power Automate",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Automate business workflows using Microsoft Power Automate, including flows, connectors, and integrations",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,400.00",
    "startDate": "11 May 2026",
    "deadline": "4 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/news/course-schedule/23097",
    "featured": false
  },
  {
    "id": "c004",
    "title": "Introduction to Web Design",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Build responsive websites using HTML, CSS, and JavaScript fundamentals",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,000.00",
    "startDate": "27 Aug 2026",
    "deadline": "20 Aug 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/introduction-web-design",
    "featured": false
  },
  {
    "id": "c005",
    "title": "Microsoft Word",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn document creation, formatting, styles, tables, and professional word processing",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$350.00",
    "startDate": "17 Aug 2026",
    "deadline": "9 Jul 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/microsoft-word",
    "featured": false
  },
  {
    "id": "c006",
    "title": "CompTIA Server+",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn server administration including hardware, virtualisation, storage, and network infrastructure",
    "type": "Short Course",
    "category": "Technology",
    "cost": "$2,500.00",
    "startDate": "15 Jun 2026",
    "deadline": "7 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/news/course-schedule/23309",
    "featured": false
  },
  {
    "id": "c007",
    "title": "Fundamentals of Project Management",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Understand project lifecycle including initiation, planning, execution, monitoring, and closure",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "$1,500.00",
    "startDate": "15 Jun 2026",
    "deadline": "7 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/fundamentals-project-management",
    "featured": false
  },
  {
    "id": "c008",
    "title": "CompTIA Security+",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn cybersecurity fundamentals including threats, risk management, cryptography, and network security",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$2,500.00",
    "startDate": "17 Aug 2026",
    "deadline": "9 Aug 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/comptia-security-plus",
    "featured": true
  },
  {
    "id": "c009",
    "title": "Database Design Fundamentals",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn relational database design, ER modelling, normalisation, and SQL basics",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,000.00",
    "startDate": "15 Sep 2026",
    "deadline": "8 Sep 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/database-design-fundamentals",
    "featured": false
  },
  {
    "id": "c010",
    "title": "Computer Literacy",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Basic computer skills including operating systems, Microsoft Office, email, and internet use",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$500.00",
    "startDate": "21 Jul 2026",
    "deadline": "13 Jul 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/computer-literacy",
    "featured": false
  },
  {
    "id": "c011",
    "title": "Enhancing Business Productivity with AI",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Use AI tools to automate tasks, improve workflows, and increase workplace efficiency",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "Level 1: $1,000 Level 2: $1,200",
    "startDate": "2 Jun 2026",
    "deadline": "25 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/business-certifications/enhancing-business-productivity-ai",
    "featured": false
  },
  {
    "id": "c012",
    "title": "CCNA (Cisco Certified Network Associate)",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn networking fundamentals including routing, switching, IP connectivity, and network security",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$3,500.00",
    "startDate": "23 Jun 2026",
    "deadline": "15 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/ccna",
    "featured": false
  },
  {
    "id": "c013",
    "title": "Computer Literacy",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Basic digital skills including OS use, Microsoft Office, internet navigation, and email",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$500.00",
    "startDate": "23 May 2026",
    "deadline": "15 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/computer-literacy",
    "featured": false
  },
  {
    "id": "c014",
    "title": "Canva Essentials",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Create graphics, presentations, and social media content using Canva tools",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,200.00",
    "startDate": "27 Jun 2026",
    "deadline": "19 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/canva-essentials",
    "featured": false
  },
  {
    "id": "c015",
    "title": "Graphic Design",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn Adobe Photoshop and Illustrator for digital design, image editing, and layout creation",
    "type": "Short Course",
    "category": "Creative Arts & Design",
    "cost": "$900.00",
    "startDate": "28 May 2026",
    "deadline": "20 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/it-certifications/adobe-photoshop-and-illustrator",
    "featured": true
  },
  {
    "id": "c016",
    "title": "Balloon Decoration",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Create balloon d\u00e9cor including arches, columns, clusters, and event designs",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$500.00",
    "startDate": "24 May 2026",
    "deadline": "16 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/balloon-decoration",
    "featured": false
  },
  {
    "id": "c017",
    "title": "Air Conditioning (Residential)",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn installation, maintenance, and troubleshooting of home air conditioning units",
    "type": "Workshop",
    "category": "Technical Trades",
    "cost": "$1,800.00",
    "startDate": "27 Jul 2026",
    "deadline": "12 Jul 2026",
    "delivery": "Hybrid",
    "location": "Hybrid",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/the-fundamentals-of-air-conditioning",
    "featured": false
  },
  {
    "id": "c018",
    "title": "Auto Air Conditioning",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Diagnose and repair vehicle air conditioning systems",
    "type": "Workshop",
    "category": "Technical Trades",
    "cost": "$1,500.00",
    "startDate": "27 Jul 2026",
    "deadline": "5 Jul 2026",
    "delivery": "Hybrid",
    "location": "Hybrid",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/the-fundamentals-of-auto-air-conditioning",
    "featured": false
  },
  {
    "id": "c019",
    "title": "The Fundamentals of Plumbing",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn basic plumbing systems including pipes, fittings, and residential repairs",
    "type": "Workshop",
    "category": "Technical Trades",
    "cost": "$1,200.00",
    "startDate": "23 May 2026",
    "deadline": "15 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/the-fundamentals-of-plumbing",
    "featured": false
  },
  {
    "id": "c020",
    "title": "Smart Phone & Tablet Repairs",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Diagnose and repair mobile devices including hardware and software issues",
    "type": "Short Course",
    "category": "Technical Trades",
    "cost": "$1,400.00",
    "startDate": "26 May 2026",
    "deadline": "18 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/smart-phone-and-tablet-repairs",
    "featured": false
  },
  {
    "id": "c021",
    "title": "Event Management",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Plan and manage events including budgeting, logistics, vendors, and execution",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$1,500.00",
    "startDate": "27 May 2026",
    "deadline": "19 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/business-certifications/event-management",
    "featured": false
  },
  {
    "id": "c022",
    "title": "Mastering Interior Decorating",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn interior styling including space planning, colour use, and home d\u00e9cor design",
    "type": "Short Course",
    "category": "Creative Arts & Design",
    "cost": "$1,200.00",
    "startDate": "23 May 2026",
    "deadline": "15 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/mastering-interior-decorating",
    "featured": false
  },
  {
    "id": "c023",
    "title": "Intro to Solar Power Systems",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn solar PV systems, installation basics, and maintenance principles",
    "type": "Short Course",
    "category": "Technical Trades",
    "cost": "$2,500.00",
    "startDate": "26 Sep 2026",
    "deadline": "18 Sep 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/introduction-solar-power-systems",
    "featured": false
  },
  {
    "id": "c024",
    "title": "Paper Flower Crafting",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Create decorative paper flowers for events and visual displays",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$500.00",
    "startDate": "8 Aug 2026",
    "deadline": "31 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/paper-flower-crafting",
    "featured": false
  },
  {
    "id": "c025",
    "title": "The Art of Candle Making",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn candle production including wax handling, fragrance blending, and moulding",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$1,000.00",
    "startDate": "25 Jul 2026",
    "deadline": "15 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/candle-making",
    "featured": false
  },
  {
    "id": "c026",
    "title": "The Art of Cookie Decorating",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn icing, piping, and decorative techniques for cookies",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$500.00",
    "startDate": "25 Jun 2026",
    "deadline": "17 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/cookie-decorating",
    "featured": false
  },
  {
    "id": "c027",
    "title": "The Art of Soap Making",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn cold and hot process soap making techniques",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$700.00",
    "startDate": "25 Jul 2026",
    "deadline": "17 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/soap-making",
    "featured": false
  },
  {
    "id": "c028",
    "title": "Advanced Industrial Relations Workshop",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn advanced industrial relations including grievance handling, disputes, and labour law",
    "type": "Workshop",
    "category": "Law & Governance",
    "cost": "$1,000.00",
    "startDate": "23 Jul 2026",
    "deadline": "15 Jul 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com",
    "featured": false
  },
  {
    "id": "c029",
    "title": "Introduction to Personal Financial Management",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn budgeting, savings, debt control, and personal financial planning",
    "type": "Short Course",
    "category": "Finance & Accounting",
    "cost": "$1,000.00",
    "startDate": "13 Jun 2026",
    "deadline": "5 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/introduction-financial-management",
    "featured": false
  },
  {
    "id": "c030",
    "title": "Mastering Sales & Marketing",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn sales techniques, marketing strategies, CRM, and customer conversion methods",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "$1,200.00",
    "startDate": "17 Jun 2026",
    "deadline": "9 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/mastering-sales-marketing",
    "featured": false
  },
  {
    "id": "c031",
    "title": "Conflict Resolution and Negotiation Skills",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Develop skills in resolving workplace conflict and negotiating effectively",
    "type": "Short Course",
    "category": "Business",
    "cost": "$1,000.00",
    "startDate": "2 Jun 2026",
    "deadline": "25 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://mailchi.mp/ctscollege/conflict-resolution-negotiation-skills",
    "featured": false
  },
  {
    "id": "c032",
    "title": "Mastering Minute Writing",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn professional minute writing for meetings, accuracy, and documentation",
    "type": "Workshop",
    "category": "Business",
    "cost": "$500.00",
    "startDate": "27 Jun 2026",
    "deadline": "19 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://mailchi.mp/ctscollege/minutewriting",
    "featured": false
  },
  {
    "id": "c033",
    "title": "Event Management",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn event planning including budgeting, logistics, vendor coordination, and execution",
    "type": "Short Course",
    "category": "Business",
    "cost": "$1,500.00",
    "startDate": "27 May 2026",
    "deadline": "19 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/news/course-schedule/23604",
    "featured": false
  },
  {
    "id": "c034",
    "title": "Fundamentals of Law",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Understand basic legal principles including contracts, tort, and company law",
    "type": "Short Course",
    "category": "Law & Governance",
    "cost": "$1,000.00",
    "startDate": "29 Jun 2026",
    "deadline": "21 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://mailchi.mp/ctscollege/fundamentals-law",
    "featured": false
  },
  {
    "id": "c035",
    "title": "Human Resource Management",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn HR functions including recruitment, training, performance, and labour law",
    "type": "Short Course",
    "category": "Business",
    "cost": "$1,000.00",
    "startDate": "19 May 2026",
    "deadline": "11 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/human-resource-management",
    "featured": false
  },
  {
    "id": "c036",
    "title": "Investigative Interviewing and Report Writing",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn structured interviewing techniques and professional report writing",
    "type": "Workshop",
    "category": "Business",
    "cost": "$1,000.00",
    "startDate": "6 Jun 2026",
    "deadline": "29 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://mailchi.mp/ctscollege/investigative-interviewing-report-writing",
    "featured": false
  },
  {
    "id": "c037",
    "title": "Public Speaking",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn speech delivery, presentation skills, and audience engagement",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "$1,000.00",
    "startDate": "26 May 2026",
    "deadline": "18 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/news/course-schedule/23467",
    "featured": false
  },
  {
    "id": "c038",
    "title": "Spanish Conversation for Beginners",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn basic Spanish vocabulary and conversational phrases",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "$800.00",
    "startDate": "4 Jun 2026",
    "deadline": "27 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/business-certifications/spanish-conversation-for-beginners",
    "featured": false
  },
  {
    "id": "c039",
    "title": "The Art of Cooking",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn culinary techniques, cooking methods, and food presentation",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$2,500.00",
    "startDate": "6 Jun 2026",
    "deadline": "29 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/certifications/do-it-yourself/cooking",
    "featured": false
  },
  {
    "id": "c040",
    "title": "Phlebotomy Technician Bridging Programme",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Upgrade skills for certified phlebotomy practitioners",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$800.00",
    "startDate": "24 Jun 2026",
    "deadline": "16 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/news/course-schedule/22947",
    "featured": false
  },
  {
    "id": "c041",
    "title": "Phlebotomy Technician Level 2",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn advanced blood collection, specimen handling, and patient care",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$2,000.00",
    "startDate": "3 Aug 2026",
    "deadline": "26 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/news/course-schedule/22593",
    "featured": false
  },
  {
    "id": "c042",
    "title": "Phlebotomy Technician Level 1",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn basic venepuncture and specimen collection",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$1,500.00",
    "startDate": "3 Aug 2026",
    "deadline": "26 Jul 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/certifications/professional-development-certifications/phlebotomy-technician",
    "featured": false
  },
  {
    "id": "c043",
    "title": "Emergency First Responder",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn emergency response including CPR, AED, and first aid",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$1,200.00",
    "startDate": "23 May 2026",
    "deadline": "15 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.ctscollege.com/news/course-schedule/23600",
    "featured": false
  },
  {
    "id": "c044",
    "title": "Introduction to Psychology",
    "institutionId": "cts",
    "institutionName": "CTS College",
    "summary": "Learn basic psychological theories and human behaviour",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$1,200.00",
    "startDate": "7 Sep 2026",
    "deadline": "29 Aug 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.ctscollege.com/news/course-schedule/23495",
    "featured": false
  },
  {
    "id": "c045",
    "title": "AI Literacy and Productivity Fundamentals",
    "institutionId": "mic",
    "institutionName": "MIC Institute of Technology (MIC-IT)",
    "summary": "Understand AI basics and use AI tools for everyday productivity tasks",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$800.00",
    "startDate": "May 2026",
    "deadline": "Apr 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.mic.co.tt/short-courses/",
    "featured": false
  },
  {
    "id": "c046",
    "title": "AI Systems, Automation and Strategic Integration",
    "institutionId": "mic",
    "institutionName": "MIC Institute of Technology (MIC-IT)",
    "summary": "Learn advanced AI use for automation, workflow design, and business integration",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,399 (Cohort 1) / $1,500 (Cohorts 2\u201310)",
    "startDate": "16 May 2026",
    "deadline": "Apr 2026",
    "delivery": "Hybrid",
    "location": "Hybrid",
    "website": "https://www.mic.co.tt/short-courses/",
    "featured": false
  },
  {
    "id": "c047",
    "title": "Introduction to Automotive Servicing & Maintenance",
    "institutionId": "mic",
    "institutionName": "MIC Institute of Technology (MIC-IT)",
    "summary": "Learn basic vehicle servicing, maintenance, and repair principles",
    "type": "Short Course",
    "category": "Technical Trades",
    "cost": "Check with Provider",
    "startDate": "11 May 2026",
    "deadline": "4 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.mic.co.tt/short-courses/",
    "featured": false
  },
  {
    "id": "c048",
    "title": "Introduction to Electrical Installation (Domestic Wiring)",
    "institutionId": "mic",
    "institutionName": "MIC Institute of Technology (MIC-IT)",
    "summary": "Learn basic domestic wiring and electrical installation techniques",
    "type": "Short Course",
    "category": "Technical Trades",
    "cost": "$1,200.00",
    "startDate": "11 May 2026",
    "deadline": "Apr 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.mic.co.tt/short-courses/",
    "featured": false
  },
  {
    "id": "c049",
    "title": "Costing and Pricing",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn how to calculate costs and set prices for products and services",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c050",
    "title": "Tendering for Contracts",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn procurement processes and how to prepare competitive tender submissions",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c051",
    "title": "Customer Relationship Management (CRM)",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn CRM systems, customer engagement, and relationship management strategies",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c052",
    "title": "Social Media Strategy for MSEs",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn how to build brand presence and marketing strategies using social media",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c053",
    "title": "Digital Transformation & E-Business Management",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn digital business models, automation, and e-business strategies",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c054",
    "title": "Taxation for Business Owners",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn business tax systems including VAT, income tax, and compliance requirements",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c055",
    "title": "Record Keeping and Cash Management",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn financial records management and cash flow control",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c056",
    "title": "Customer Service Excellence",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn communication skills and techniques for delivering excellent customer service",
    "type": "Workshop",
    "category": "Hospitality & Culinary",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c057",
    "title": "Negotiation Skills for Business Owners",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn negotiation strategies for business deals and stakeholder interactions",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c058",
    "title": "Facilities Management for Small Business",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn maintenance planning, budgeting, and facilities operations management",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c059",
    "title": "Steps to Starting Your Business",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn how to register, plan, and start a small business in Trinidad and Tobago",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c060",
    "title": "Basic Human Resources for Small Business",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn HR basics including hiring, payroll, discipline, and staff management",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c061",
    "title": "Business Etiquette and Protocol",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn professional communication, etiquette, and business conduct",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c062",
    "title": "Buying and Stock Control",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn inventory management and stock control systems",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c063",
    "title": "Productivity and People Management",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn how to manage teams and improve workforce productivity",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c064",
    "title": "Managing a Limited Liability Company",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn legal structure, governance, and compliance for companies",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c065",
    "title": "Competitive Strategy for Small Business",
    "institutionId": "nedco",
    "institutionName": "National Entrepreneurship Development Company Limited (NEDCO)",
    "summary": "Learn how to develop competitive advantage and business strategy",
    "type": "Workshop",
    "category": "Business & Entrepreneurship",
    "cost": "$400.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online or In-person",
    "location": "F2F or Online",
    "website": "https://nedco.gov.tt/services/training/one-day-courses",
    "featured": false
  },
  {
    "id": "c066",
    "title": "Food Costing and Pricing",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn food costing, recipe pricing, and profitability control",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$1,245.00",
    "startDate": "1 Jul 2026",
    "deadline": "23 Jun 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.thti.edu.tt",
    "featured": false
  },
  {
    "id": "c067",
    "title": "A Complete Guide to Payroll",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn payroll processing including deductions, salaries, and compliance",
    "type": "Short Course",
    "category": "Finance & Accounting",
    "cost": "$795.00",
    "startDate": "1 Jun 2026",
    "deadline": "24 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.thti.edu.tt",
    "featured": false
  },
  {
    "id": "c068",
    "title": "Baking Boot Camp I & II",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn foundational and intermediate baking techniques",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$1,500.00",
    "startDate": "10 Aug 2026",
    "deadline": "2 Aug 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt",
    "featured": true
  },
  {
    "id": "c069",
    "title": "Introduction to Bookkeeping & Accounting",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn basic accounting, financial statements, and bookkeeping",
    "type": "Short Course",
    "category": "Finance & Accounting",
    "cost": "$1,245.00",
    "startDate": "10 Sep 2026",
    "deadline": "2 Sep 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.thti.edu.tt/product/introduction-to-bookkeeping-accounting/",
    "featured": false
  },
  {
    "id": "c070",
    "title": "Food Preparation",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn cooking techniques, food safety, and kitchen operations",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$2,195.00",
    "startDate": "19 May 2026",
    "deadline": "11 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/food-preparation/",
    "featured": true
  },
  {
    "id": "c071",
    "title": "Bartending & Mixology",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn cocktail preparation, bar operations, and beverage service",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$2,295.00",
    "startDate": "2 May 2026",
    "deadline": "25 Apr 2026",
    "delivery": "Hybrid",
    "location": "Blended (Online + F2F)",
    "website": "https://www.thti.edu.tt/product/bartending-mixology/",
    "featured": true
  },
  {
    "id": "c072",
    "title": "The Art of Bread Making (Lean & Rich Bread)",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Master lean and rich bread techniques in this hands-on baking workshop",
    "type": "Workshop",
    "category": "Hospitality & Culinary",
    "cost": "$695.00",
    "startDate": "26 May 2026",
    "deadline": "18 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/the-art-of-bread-making-2/",
    "featured": false
  },
  {
    "id": "c073",
    "title": "Housekeeping Skills",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn professional cleaning standards and hospitality housekeeping",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$1,345.00",
    "startDate": "27 May 2026",
    "deadline": "19 May 2026",
    "delivery": "Hybrid",
    "location": "Blended (Online + F2F)",
    "website": "https://www.thti.edu.tt/product/housekeeping-skills/",
    "featured": false
  },
  {
    "id": "c074",
    "title": "Fundamentals of Quick Breads and Cakes",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn baking basics including muffins, sponge cakes, and quick breads",
    "type": "Workshop",
    "category": "Hospitality & Culinary",
    "cost": "$2,295.00",
    "startDate": "6 Jun 2026",
    "deadline": "29 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/the-art-of-cakes-and-quick-breads/",
    "featured": false
  },
  {
    "id": "c075",
    "title": "The Art of Laminated Pastry",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn advanced pastry techniques including croissants and puff pastry",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$2,295.00",
    "startDate": "8 Aug 2026",
    "deadline": "31 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/the-art-of-laminated-pastry/",
    "featured": false
  },
  {
    "id": "c076",
    "title": "Contemporary Caribbean Cuisine",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn modern Caribbean cooking techniques and plating styles",
    "type": "Workshop",
    "category": "Hospitality & Culinary",
    "cost": "$995.00",
    "startDate": "8 Jul 2026",
    "deadline": "30 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/contemporary-caribbean-cuisine/",
    "featured": false
  },
  {
    "id": "c077",
    "title": "Mastering the Art of Ponche de Cr\u00e8me",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn preparation and presentation of traditional Ponche de Cr\u00e8me",
    "type": "Workshop",
    "category": "Hospitality & Culinary",
    "cost": "$795.00",
    "startDate": "TBC 2026",
    "deadline": "Contact provider",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.thti.edu.tt/product/mastering-the-art-of-ponche-de-creme/",
    "featured": false
  },
  {
    "id": "c078",
    "title": "Layer and Broiler Production",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn poultry farming systems and production management",
    "type": "Short Course",
    "category": "Agriculture & Environment",
    "cost": "$495.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.thti.edu.tt",
    "featured": false
  },
  {
    "id": "c079",
    "title": "Homestead Farming",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn small-scale agriculture and livestock management",
    "type": "Short Course",
    "category": "Agriculture & Environment",
    "cost": "$495.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online / F2F",
    "location": "Online / F2F",
    "website": "https://www.thti.edu.tt",
    "featured": false
  },
  {
    "id": "c080",
    "title": "Beverage Costing and Pricing",
    "institutionId": "thti",
    "institutionName": "Trinidad and Tobago Hospitality and Tourism Institute (THTI)",
    "summary": "Learn costing and pricing for beverage operations",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$1,245.00",
    "startDate": "Rolling 2026",
    "deadline": "Contact provider",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.thti.edu.tt/product/beverage-costing-and-pricing/",
    "featured": false
  },
  {
    "id": "c081",
    "title": "Broadcasting & Communication Essentials",
    "institutionId": "roytec",
    "institutionName": "UWI-ROYTEC",
    "summary": "Learn media communication and broadcasting fundamentals",
    "type": "Short Course",
    "category": "Communication & Media",
    "cost": "$1,450.00",
    "startDate": "25 May 2026",
    "deadline": "18 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://www.roytec.edu/corporate-training/schedule",
    "featured": false
  },
  {
    "id": "c082",
    "title": "Applied AI for Professional and Personal Use (Level 2)",
    "institutionId": "roytec",
    "institutionName": "UWI-ROYTEC",
    "summary": "Use AI tools for productivity, caregiving support, and applied workplace tasks",
    "type": "Workshop",
    "category": "Technology & Digital",
    "cost": "$1,000.00",
    "startDate": "26 May 2026",
    "deadline": "18 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://www.roytec.edu",
    "featured": false
  },
  {
    "id": "c083",
    "title": "Intelligence Analysis",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Learn methods of collecting, evaluating, and interpreting information to support structured analysis and decision-making",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$7,500.00",
    "startDate": "8 Jun 2026",
    "deadline": "31 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c084",
    "title": "Risk Management and Resilience",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Understand risk identification, assessment, mitigation strategies, and building organisational resilience",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$4,000.00",
    "startDate": "15 Jun 2026",
    "deadline": "7 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c085",
    "title": "Real Estate Brokerage and Agency Principles",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Learn real estate practice including property marketing, brokerage operations, and agency responsibilities",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$4,000.00",
    "startDate": "1 Jun 2026",
    "deadline": "24 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c086",
    "title": "Family Life Education Basic",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Develop foundational knowledge in family support, communication, and healthy family relationships",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$1,500.00",
    "startDate": "1 Jun 2026",
    "deadline": "24 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c087",
    "title": "Family Life Education Advanced",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Build advanced skills in family support strategies, guidance, and community-based family development",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$2,000.00",
    "startDate": "1 Jun 2026",
    "deadline": "24 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c088",
    "title": "Music Production and Sound Engineering",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Learn audio recording, sound design, mixing, and basic music production techniques",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "$3,000.00",
    "startDate": "1 Jul 2026",
    "deadline": "23 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c089",
    "title": "Youth Leadership in Sports",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Develop leadership skills for guiding youth development through sport and physical activity programmes",
    "type": "Short Course",
    "category": "Soft Skills",
    "cost": "$3,000.00",
    "startDate": "6 Jul 2026",
    "deadline": "28 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c090",
    "title": "Multimedia Painting",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Explore creative expression using digital and traditional painting techniques across multiple media",
    "type": "Short Course",
    "category": "Soft Skills",
    "cost": "$3,000.00",
    "startDate": "6 Jul 2026",
    "deadline": "28 Jun 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c091",
    "title": "Fundamentals of Video Editing",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Learn basic video editing skills including cutting, sequencing, transitions, and storytelling structure",
    "type": "Workshop",
    "category": "Creative Arts & Design",
    "cost": "$3,000.00",
    "startDate": "14 Jul 2026",
    "deadline": "6 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c092",
    "title": "Foundations of Vegetarian Cuisine",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Drawing and painting techniques",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$3,000.00",
    "startDate": "3 Aug 2026",
    "deadline": "26 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c093",
    "title": "Fancy Homemade Desserts",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Understand vegetarian cooking principles, meal preparation techniques, and basic nutrition concepts",
    "type": "Short Course",
    "category": "Hospitality & Culinary",
    "cost": "$3,000.00",
    "startDate": "3 Aug 2026",
    "deadline": "26 Jul 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c094",
    "title": "Social Media and Corporate Video Production",
    "institutionId": "usc",
    "institutionName": "University of the Southern Caribbean (USC)",
    "summary": "Learn preparation and presentation techniques for creative desserts and basic pastry methods",
    "type": "Short Course",
    "category": "Communication & Media",
    "cost": "$3,000.00",
    "startDate": "25 Aug 2026",
    "deadline": "17 Aug 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://usc.edu.tt/academics/professional-development-institute/",
    "featured": false
  },
  {
    "id": "c095",
    "title": "First Aid, CPR and AED",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "Learn basic first aid, CPR techniques, and use of AED for emergency life-saving response",
    "type": "Short Course",
    "category": "Health & Medical",
    "cost": "$1,800.00",
    "startDate": "27 Oct 2026",
    "deadline": "19 Oct 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://peutraining.utt.edu.tt/modules/shop/index.html?action=section&OfferingID=156",
    "featured": true
  },
  {
    "id": "c096",
    "title": "Inventory and Warehouse Management",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "Learn inventory control systems, warehouse processes, stock tracking, and supply chain fundamentals",
    "type": "Short Course",
    "category": "Engineering & Construction",
    "cost": "$2,800.00",
    "startDate": "May 4, 2026",
    "deadline": "May 4, 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://peutraining.utt.edu.tt/modules/shop/index.html?action=section&OfferingID=146989",
    "featured": false
  },
  {
    "id": "c097",
    "title": "Effective Public Speaking",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "Develop clear communication skills, presentation delivery, and confidence in public speaking settings",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "$2,800.00",
    "startDate": "26 Jul 2026",
    "deadline": "18 Jul 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://peutraining.utt.edu.tt/modules/shop/index.html?action=section&OfferingID=1517",
    "featured": false
  },
  {
    "id": "c098",
    "title": "Mastering Supervisory Management",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "Build supervisory skills in leadership, performance management, and workplace coordination",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "$3,000.00",
    "startDate": "18 May 2026",
    "deadline": "18 May 2026",
    "delivery": "In-person",
    "location": "In-person",
    "website": "https://peutraining.utt.edu.tt/modules/shop/index.html?action=section&OfferingID=144067",
    "featured": false
  },
  {
    "id": "c099",
    "title": "Records and Information Management Strategies",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "Learn how to manage records, organise information systems, and maintain proper documentation control",
    "type": "Short Course",
    "category": "Business",
    "cost": "$2,800.00",
    "startDate": "18 May 2026",
    "deadline": "17 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://peutraining.utt.edu.tt/modules/shop/index.html?action=section&OfferingID=178767",
    "featured": false
  },
  {
    "id": "c100",
    "title": "Train the Trainer",
    "institutionId": "alj",
    "institutionName": "Arthur Lok Jack Global School of Business",
    "summary": "Develop skills to design and deliver training sessions and facilitate workplace learning",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "Contact Provider",
    "startDate": "13 Jul 2026",
    "deadline": "5 Jul 2026",
    "delivery": "Contact Provider",
    "location": "Contact Provider",
    "website": "https://lokjackgsb.edu.tt/short-courses/train-the-trainer/",
    "featured": true
  },
  {
    "id": "c101",
    "title": "Effective Business Writing",
    "institutionId": "alj",
    "institutionName": "Arthur Lok Jack Global School of Business",
    "summary": "Improve professional writing for business communication, reports, and workplace documents",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "Contact Provider",
    "startDate": "18 May 2026",
    "deadline": "10 May 2026",
    "delivery": "Online",
    "location": "Online",
    "website": "https://lokjackgsb.edu.tt/short-courses/effective-business-writing/",
    "featured": false
  },
  {
    "id": "c102",
    "title": "Excel Proficiency Advanced Skills for Professionals",
    "institutionId": "alj",
    "institutionName": "Arthur Lok Jack Global School of Business",
    "summary": "Develop advanced Excel skills for data analysis, reporting, formulas, and productivity tools",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "Contact Provider",
    "startDate": "April 30, 2026",
    "deadline": "Register 1 week before start",
    "delivery": "Contact Provider",
    "location": "Contact Provider",
    "website": "https://lokjackgsb.edu.tt/short-courses/advanced-ms-excel/",
    "featured": false
  },
  {
    "id": "c103",
    "title": "Administrative Support",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Build practical administrative skills for workplace organisation, communication, and daily office support tasks",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/administrative-support/",
    "featured": false
  },
  {
    "id": "c104",
    "title": "Administrative Office Procedures",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Learn structured office workflows including documentation, filing systems, and routine administrative processes",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/administrative-office-procedures/",
    "featured": false
  },
  {
    "id": "c105",
    "title": "Trust Building and Resilience Development",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Develop workplace trust, improve communication, and strengthen the ability to handle pressure and change",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/trust-building-and-resilience-development/",
    "featured": false
  },
  {
    "id": "c106",
    "title": "Developing Emotional Intelligence",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Improve self-awareness, emotional control, empathy, and interpersonal communication in professional settingsI",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/emotional-intelligence/",
    "featured": false
  },
  {
    "id": "c107",
    "title": "Team Building Through Chemistry",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Strengthen team relationships, collaboration, and group performance in the workplace",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/team-building-through-chemistry/",
    "featured": false
  },
  {
    "id": "c108",
    "title": "Overcoming Sales Objections",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Learn how to respond to customer concerns and improve conversion during the sales process",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/overcoming-sales-objections/",
    "featured": false
  },
  {
    "id": "c109",
    "title": "Team Building for Managers",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Develop leadership skills to improve team coordination, performance, and workplace morale",
    "type": "Short Course",
    "category": "Personal Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/team-building-for-managers/",
    "featured": false
  },
  {
    "id": "c110",
    "title": "Teamwork and Team Building",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Build collaboration skills to improve group effectiveness and workplace cooperation",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/teamwork-and-team-building/",
    "featured": false
  },
  {
    "id": "c111",
    "title": "Motivating Your Sales Team",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Learn strategies to inspire sales teams and improve overall performance and results",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/motivating-your-sales-team/",
    "featured": false
  },
  {
    "id": "c112",
    "title": "Sales Fundamentals",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Understand core sales processes including customer engagement, negotiation, and closing techniques",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/sales-fundamentals/",
    "featured": false
  },
  {
    "id": "c113",
    "title": "Social Media Marketing",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Learn how to create content, manage platforms, and apply basic digital marketing strategies",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/social-media-marketing/",
    "featured": true
  },
  {
    "id": "c114",
    "title": "Marketing Basics",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Understand core marketing principles including audience targeting, branding, and campaign planning",
    "type": "Short Course",
    "category": "Business & Entrepreneurship",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/marketing-basics/",
    "featured": false
  },
  {
    "id": "c115",
    "title": "Human Resource Management",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Learn essential HR functions including recruitment, employee relations, and workforce coordination",
    "type": "Short Course",
    "category": "Professional Development",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/human-resource-management/",
    "featured": false
  },
  {
    "id": "c116",
    "title": "Cyber Security",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Gain awareness of cyber risks, safe digital practices, and basic data protection methods",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/cyber-security/",
    "featured": false
  },
  {
    "id": "c117",
    "title": "Creative Arts & Design",
    "institutionId": "shel",
    "institutionName": "School of Higher Education Limited - SHEL",
    "summary": "Build a strong professional identity and improve how you present yourself in career and online spaces",
    "type": "Short Course",
    "category": "Creative Arts & Design",
    "cost": "125 USD",
    "startDate": "Self-paced",
    "deadline": "Open",
    "delivery": "Online",
    "location": "Online",
    "website": "https://shel.edu.tt/personal-branding/",
    "featured": false
  },
  {
    "id": "c118",
    "title": "Applied AI for Professionals",
    "institutionId": "utt",
    "institutionName": "University of Trinidad and Tobago (UTT)",
    "summary": "A practical introduction to artificial intelligence and machine learning concepts, tools, and real-world applications — designed for working professionals across all industries.",
    "type": "Short Course",
    "category": "Technology & Digital",
    "cost": "$1,500.00",
    "startDate": "09 Jun 2026",
    "deadline": "26 May 2026",
    "delivery": "Hybrid",
    "location": "Multiple campuses",
    "website": "https://utt.edu.tt",
    "featured": true
  }
];

const ONLINE_GUIDES = [
  {
    id: 'og1',
    skill: 'AI Literacy',
    title: 'Google AI Essentials',
    provider: 'Google',
    platform: 'Coursera',
    duration: '~10 hours',
    certificate: true,
    cost: '~$49/month',
    free: false,
    freeAccess: '7-day free trial',
    roles: 'Business, government, customer support',
    pitch: 'The AI briefing your career needs. Learn to use AI tools across operations, communications, and strategy — certified by the team that built them.',
    url: 'https://www.coursera.org/specializations/ai-essentials-google',
  },
  {
    id: 'og2',
    skill: 'Programming',
    title: 'Python for Everybody',
    provider: 'University of Michigan',
    platform: 'Coursera',
    duration: '4–6 months',
    certificate: true,
    cost: '~$39–$49/month',
    free: false,
    freeAccess: '7-day free trial + audit access',
    roles: 'Data, software, automation, finance systems',
    pitch: 'Data analysis, automation, finance systems — they all run on Python. Start from zero, finish job-ready with a credential from one of the world\'s top universities.',
    url: 'https://www.coursera.org/specializations/python',
  },
  {
    id: 'og3',
    skill: 'UX Design',
    title: 'Google UX Design Certificate',
    provider: 'Google',
    platform: 'Coursera',
    duration: '~6 months',
    certificate: true,
    cost: '~$39–$49/month',
    free: false,
    freeAccess: '7-day free trial',
    roles: 'Apps, banking platforms, digital services',
    pitch: 'Design the products Caribbean businesses are building. Six months, a Google certificate, and a portfolio that speaks for itself in any interview room.',
    url: 'https://www.coursera.org/professional-certificates/google-ux-design',
  },
  {
    id: 'og4',
    skill: 'Renewable Energy',
    title: 'Introduction to Renewable Energy',
    provider: 'University of Colorado Boulder',
    platform: 'Coursera',
    duration: '~8–10 hours',
    certificate: true,
    cost: '~$39–$79',
    free: false,
    freeAccess: '7-day free trial + audit access',
    roles: 'Energy transition, oil & gas shift, sustainability',
    pitch: 'The energy sector is shifting. Get ahead of T&T\'s transition from fossil fuels to solar, wind, and sustainable infrastructure — before everyone else does.',
    url: 'https://www.coursera.org/learn/introduction-to-renewable-energy',
  },
  {
    id: 'og5',
    skill: 'Digital Marketing',
    title: 'Fundamentals of Digital Marketing',
    provider: 'Google',
    platform: 'Google Digital Garage',
    duration: '~40 hours',
    certificate: true,
    cost: 'Free',
    free: true,
    freeAccess: 'Fully free',
    roles: 'Marketing, SMEs, freelance, ecommerce',
    pitch: '40 hours. A Google certificate. Zero cost. The most practical digital qualification any T&T business owner, freelancer, or marketer can add to their résumé right now.',
    url: 'https://learndigital.withgoogle.com/digitalgarage',
  },
  {
    id: 'og6',
    skill: 'Content Marketing',
    title: 'Content Marketing Certification',
    provider: 'HubSpot',
    platform: 'HubSpot Academy',
    duration: '~6 hours',
    certificate: true,
    cost: 'Free',
    free: true,
    freeAccess: 'Fully free',
    roles: 'Branding, social media, freelancing',
    pitch: 'Turn strategy into content that actually converts. HubSpot\'s free certification is the baseline credential for anyone serious about building a brand or a client base.',
    url: 'https://academy.hubspot.com/courses/content-marketing',
  },
  {
    id: 'og7',
    skill: 'Email Marketing',
    title: 'Email Marketing Certification',
    provider: 'HubSpot',
    platform: 'HubSpot Academy',
    duration: '~4 hours',
    certificate: true,
    cost: 'Free',
    free: true,
    freeAccess: 'Fully free',
    roles: 'CRM, business marketing, SMEs',
    pitch: 'Still the highest-ROI channel in digital marketing. Four hours and a free HubSpot certification you can apply to your next campaign before the week is out.',
    url: 'https://academy.hubspot.com/courses/email-marketing',
  },
  {
    id: 'og8',
    skill: 'Social Media Ads',
    title: 'Social Media Marketing Courses',
    provider: 'Meta',
    platform: 'Meta Blueprint',
    duration: '2–10 hours',
    certificate: true,
    cost: 'Free',
    free: true,
    freeAccess: 'Fully free',
    roles: 'Freelance ads, agency work, SMEs',
    pitch: 'Learn to run ads that actually convert — straight from Meta. The essential training for anyone managing Facebook or Instagram campaigns for local businesses.',
    url: 'https://www.facebook.com/business/learn/courses',
  },
  {
    id: 'og9',
    skill: 'SEO',
    title: 'SEO Fundamentals',
    provider: 'Semrush',
    platform: 'Semrush Academy',
    duration: '~3–6 hours',
    certificate: true,
    cost: 'Free',
    free: true,
    freeAccess: 'Fully free',
    roles: 'Digital marketing, content strategy',
    pitch: 'Get your business found on Google. Semrush\'s free certification covers the organic search strategies that drive real, lasting traffic — no ad spend required.',
    url: 'https://www.semrush.com/academy/courses/seo-fundamentals/',
  },
];

const BLOG_POSTS = [
  {
    id: 'b1',
    title: 'Explore Tech Pathways',
    excerpt: 'Curious about tech? These courses cover coding, design, data, and security. Browse what stands out.',
    topic: 'Technology & Digital',
    date: 'May 2026',
    readTime: '2 min',
    courses: [
      { name: 'Introduction to Web Design', note: 'How websites look and function' },
      { name: 'Database Design Fundamentals', note: 'Structure and manage data' },
      { name: 'Computer Literacy', note: 'Everyday digital skills' },
      { name: 'Microsoft Word', note: 'Core productivity skills' },
      { name: 'CCNA', note: 'Networking and infrastructure' },
      { name: 'CompTIA Security+', note: 'Cybersecurity basics' },
      { name: 'Enhancing Business Productivity with AI', note: 'Practical AI tools for work' },
    ],
  },
  {
    id: 'b2',
    title: 'Discover Creative and Practical Skills',
    excerpt: 'Hands-on courses you can try at your own pace. Some are creative, some are technical, all are practical.',
    topic: 'Creative & Trades',
    date: 'May 2026',
    readTime: '2 min',
    courses: [
      { name: 'Balloon Decoration', note: '' },
      { name: 'Candle Making', note: '' },
      { name: 'Soap Making', note: '' },
      { name: 'Cooking', note: '' },
      { name: 'Paper Flower Crafting', note: '' },
      { name: 'Cookie Decorating', note: '' },
      { name: 'Interior Decorating', note: '' },
      { name: 'Smartphone & Tablet Repairs', note: '' },
    ],
    footer: 'Each one opens a different kind of skill, from creative work to repair-based services.',
  },
  {
    id: 'b3',
    title: 'Browse Business and Career Skills',
    excerpt: 'Courses focused on management, communication, and building ideas into income.',
    topic: 'Business & Career',
    date: 'May 2026',
    readTime: '2 min',
    courses: [
      { name: 'Fundamentals of Project Management', note: '' },
      { name: 'Certified Associate in Project Management (CAPM)', note: '' },
      { name: 'Event Management', note: '' },
      { name: 'Mastering Sales & Marketing', note: '' },
      { name: 'Introduction to Financial Management', note: '' },
      { name: 'Human Resource Management', note: '' },
      { name: 'Conflict Resolution and Negotiation Skills', note: '' },
      { name: 'Spanish Conversation for Beginners', note: '' },
    ],
    footer: 'Explore options that support leadership, planning, and growth.',
  },
];

const FAQS = [
  {
    title: 'About CourzaTT',
    questions: [
      { question: 'What is CourzaTT?', answer: 'CourzaTT is a centralized directory of courses available in Trinidad and Tobago — across public, private, and technical institutions.' },
      { question: 'How comprehensive is the directory?', answer: 'We currently list over ' + COURSES.length + ' courses across ' + INSTITUTIONS.length + ' major institutions, updated each semester.' },
      { question: 'Who can use this platform?', answer: 'Anyone — students, working professionals, or hobbyists looking to advance their skills.' },
      { question: 'Why does CourzaTT link to other websites?', answer: 'We provide discovery and metadata. For enrollment and specific details, we direct you to the official institution website.' }
    ]
  },
  {
    title: 'For students',
    questions: [
      { question: 'Does CourzaTT provide courses?', answer: 'No, CourzaTT is a directory. The courses are provided by the listed institutions.' },
      { question: 'How do I enroll in a course?', answer: 'Click "Visit website" on any course card to go to the institution\'s official registration page.' },
      { question: 'Are the courses free?', answer: 'Costs vary. Check the "Cost" section of each course — many are paid, some are GATE funded.' },
      { question: 'Will I get a certificate?', answer: 'Certificates are awarded by the providing institution upon successful completion.' },
    ]
  },
  {
    title: 'For institutions',
    questions: [
      { question: 'How do I list my institution?', answer: 'Go to the "List Your Institution" page, fill in the form with your institution name, contact details, type, and a brief description, then click Submit. Our team will review and add you to the directory within 2–3 business days.' },
      { question: 'Is listing my courses free?', answer: 'Yes — completely free, always. Any institution can list their courses at no cost. They will appear in search results, category pages, and your institution profile from day one. Paid options are only for additional promotion and visibility.' },
      { question: 'How does CourzaTT make money?', answer: 'We charge for promotion. Institutions can pay to feature their courses on:', bullets: ['Homepage', 'Newsletter', 'Social media'] },
      { question: 'Do paid features affect rankings?', answer: 'No. All courses can be listed for free. Sponsored placements are clearly labelled and do not affect search results.' },
      { question: 'What is a sponsored listing?', answer: 'A paid placement that increases your visibility across the platform. This can include:', bullets: ['Homepage placement', 'Category priority', 'Featured badge'] },
      { question: 'Do you take a commission from course sales?', answer: 'No. We do not take a cut from course fees or enrolments.' },
      { question: 'Why offer paid placements?', answer: 'To keep the platform free for learners. This supports:', bullets: ['Course discovery across Trinidad and Tobago', 'Ongoing platform updates'] },
    ]
  }
];

window.CourzaData = { CATEGORIES, INSTITUTIONS, COURSES, BLOG_POSTS, FAQS, ONLINE_GUIDES };
